-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8A4iH4aSdM2TXOsO
RIyR7nfiZJSXzHzzkD9EXYz/lCugCgYIKoZIzj0DAQehRANCAATuGvRr4V51a3xq
OKZEzdzwdLLyBscE8Akj1ucaIi/4MqBPINoj+vkhPB+ouvOLn81WkM0h+TWsp2yO
mjadVRd3
-----END PRIVATE KEY-----