default_platform(:ios)

platform :ios do
  before_all do
    # Select the correct Xcode version for CI (if multiple versions are installed)
    xcode_select "/Applications/Xcode.app"
  end

  desc "Build the app"
  lane :build_app_only do
    build_app(
      project: "AutomationTestProject.xcodeproj",
      scheme: "AutomationTestProject",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.test.automationSampleTest" => "match AppStore com.test.automationSampleTest 1729493544"
        }
      },
      xcargs: "-verbose CODE_SIGNING_LOG=1 -showBuildTimingSummary OTHER_CODE_SIGN_FLAGS='--verbose' SWIFT_SIGNING_LOG=1"
    )
  end

 desc "Upload to TestFlight"
lane :upload_to_testflight_custom do
  upload_to_testflight(
    api_key: {
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'], 
      key: ENV['APP_STORE_CONNECT_API_KEY']  # Use the environment variable directly
    }
  )
end

  desc "Build and upload to TestFlight"
  lane :build_and_upload do
    build_app_only
    upload_to_testflight_custom
  end
end