# Force Fastlane to use the correct OpenSSL configuration
ENV["OPENSSL_CONF"] = "/usr/local/etc/openssl/openssl.cnf"

default_platform(:ios)

platform :ios do
  before_all do
    # Ensure correct Xcode version is selected
    xcode_select "/Applications/Xcode.app"
  end

  desc "Build the app"
  lane :build_app_only do
    build_app(
      project: "AutomationTestProject.xcodeproj",
      scheme: "AutomationTestProject",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "AutomationTestProject.ipa",
      export_options: {
        provisioningProfiles: {
          "com.test.automationSampleTest" => "match AppStore com.test.automationSampleTest 1729493544"
        }
      },
      xcargs: "-verbose CODE_SIGNING_LOG=1 -showBuildTimingSummary"
    )
  end

  desc "Upload to TestFlight"
  lane :upload_to_testflight_custom do
   upload_to_testflight(
  api_key: {
    key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
    issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
    key: File.read(ENV['API_KEY_PATH'])  # Use the environment variable for the path
  },
  ipa: "./build/AutomationTestProject.ipa",
  skip_waiting_for_build_processing: true,
  skip_submission: true,
  notify_external_testers: false
)
  end

  desc "Build and upload to TestFlight"
  lane :build_and_upload do
    build_app_only
    upload_to_testflight_custom
  end
end