name: Build and Export iOS App

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Xcode
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app

    # Step 3: Install dependencies using Bundler
    - name: Install Ruby gems via Bundler
      run: bundle install

    # Step 4: Install Certificate
    - name: Install certificate
      run: |
        echo "$APP_STORE_CERTIFICATE" | base64 --decode > certificate.p12
        security create-keychain -p "" build.keychain
        security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
        security list-keychains -s build.keychain
        security unlock-keychain -p "" build.keychain
      env:
        APP_STORE_CERTIFICATE: ${{ secrets.APP_STORE_CERTIFICATE }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

    # Step 5: Install Provisioning Profile
    - name: Install provisioning profile
      run: |
        echo "$PROVISIONING_PROFILE" | base64 --decode > profile.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      env:
        PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}

    # Step 6: Build and Upload to TestFlight using Fastlane
    - name: Build and Upload to TestFlight
      run: bundle exec fastlane build_and_upload
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }} # Your Apple ID email for Fastlane
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }} # App-specific password for your Apple ID
