name: Build and Upload to TestFlight

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install OpenSSL
      - name: Install OpenSSL
        run: brew install openssl

      # Step 3: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # Step 4: Install dependencies (Fastlane, CocoaPods, etc.)
      - name: Install dependencies
        run: |
          gem install bundler:2.5.21
          bundle install --jobs 4 --retry 3

      # Step 5: Decode the Base64 certificate and save it as a .p12 file
      - name: Decode Certificate
        run: |
          echo "${{ secrets.CERTIFICATE_P12_BASE64 }}" | base64 --decode > ./Certificates.p12
          
      - name: Decode and save API key
        run: |
         mkdir -p fastlane/certs
         echo "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" | base64 --decode > fastlane/certs/AuthKey_Z63U6QP7DT.p8
      # Step 6: Create and unlock the keychain
      - name: Create and unlock keychain
        run: |
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security list-keychains -s build.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security set-keychain-settings build.keychain
          security import ./Certificates.p12 -k build.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      # Step 7: Fetch certificates and provisioning profiles using Fastlane Match
      - name: Fetch certificates and provisioning profiles using Fastlane Match
        run: bundle exec fastlane match appstore --readonly
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

      # Step 8: Clean Derived Data to avoid stale cache issues
      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData

      # Step 9: Build the app
      - name: Build the app
        run: bundle exec fastlane build_app_only
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # Step 10: Upload to TestFlight
      - name: Upload to TestFlight
        run: bundle exec fastlane upload_to_testflight_custom
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}

      # Step 11: Upload Xcode Logs after build (successful or failed)
      - name: Upload Xcode Logs
        uses: actions/upload-artifact@v3
        with:
          name: xcode-build-logs
          path: ~/Library/Logs/gym/*.log

      # Step 12: Delete keychain (optional, for cleanup)
      - name: Delete keychain
        run: security delete-keychain build.keychain
