name: Build and Upload to TestFlight

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby environment for Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2' # Match your local Ruby version

    - name: Install Fastlane
      run: gem install fastlane -NV

    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app

    - name: Install certificate
      run: |
        echo "$APP_STORE_CERTIFICATE" | base64 --decode > certificate.p12
        security create-keychain -p "" build.keychain
        security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
        security list-keychains -s build.keychain
        security unlock-keychain -p "" build.keychain
      env:
        APP_STORE_CERTIFICATE: ${{ secrets.APP_STORE_CERTIFICATE }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

    - name: Install provisioning profile
      run: |
        echo "$PROVISIONING_PROFILE" | base64 --decode > profile.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      env:
        PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}

    - name: Build and Upload to TestFlight
      run: fastlane build_and_upload
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }} # Store App Store Connect API key in secrets
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }} # Your Apple ID email for Fastlane
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }} # App-specific password for your Apple ID
