name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app

    - name: Reset Simulator
      run: xcrun simctl shutdown all && xcrun simctl erase all

    - name: Boot iOS Simulator
      run: xcrun simctl boot "iPhone 11"

    - name: Build app
      run: xcodebuild clean build -project AutomationTestProject.xcodeproj -scheme AutomationTestProject -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'

    - name: Run tests
      run: xcodebuild test -project AutomationTestProject.xcodeproj -scheme AutomationTestProject -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' -destination-timeout 360

    - name: Archive build
      run: xcodebuild archive -project AutomationTestProject.xcodeproj -scheme AutomationTestProject -archivePath $PWD/build/YourApp.xcarchive

    - name: Export IPA
      run: xcodebuild -exportArchive -archivePath $PWD/build/AutomationTestProject.xcarchive -exportPath $PWD/build -exportOptionsPlist ./path/to/exportOptions.plist
