name: iOS CI # This is the name of  workflow

# Triggers that start the workflow:
on:
  push: # Run the workflow whenever code is pushed to the main branch
    branches:
      - main
  pull_request: # Run the workflow when a pull request is created targeting the main branch
    branches:
      - main

jobs:
  build: # Name of the job
    runs-on: macos-latest #  Xcode to build an iOS app

    steps:
    - name: Checkout repository # Step 1: Checkout the code from your GitHub repository
      uses: actions/checkout@v2

    - name: Set up Xcode # Step 2: Point to the correct version of Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app
      # You might need to update "Xcode_14.0.0" to match the version you're using.

    - name: Build app # Step 3: Build the app using Xcode
      run: xcodebuild clean build -workspace AutomationTestProject.xcworkspace -scheme AutomationTestProject -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14'

    - name: Run tests # Step 4: Run any tests in your project
      run: xcodebuild test -workspace AutomationTestProject.xcworkspace -scheme AutomationTestProject -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14'

    - name: Archive build # Step 5: Archive the app for distribution
      run: xcodebuild archive -workspace AutomationTestProject.xcworkspace -scheme AutomationTestProject -archivePath $PWD/build/YourApp.xcarchive

    - name: Export IPA # Step 6: Export the archived app to an .ipa file
      run: xcodebuild -exportArchive -archivePath $PWD/build/AutomationTestProject.xcarchive -exportPath $PWD/build -exportOptionsPlist ./path/to/exportOptions.plist
